name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sample-assignment-test
      id: sample-assignment-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: sample-assignment-test
        setup-command: javac task1/*.java
        command: java task1.Hello
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAMPLE-ASSIGNMENT-TEST_RESULTS: "${{steps.sample-assignment-test.outputs.result}}"
      with:
        runners: sample-assignment-test
